language: emacs-lisp
matrix:
  # Don’t wait for jobs that are allowed to fail
  fast_finish: true
  # Allow snapshot to fail
  allow_failures:
    - env: EMACS_VERSION=snapshot
cache:
  - directories:
      - .cask/
env:
  matrix:
    - EMACS_VERSION=24.4
    - EMACS_VERSION=24.5
    - EMACS_VERSION=25.1
    - EMACS_VERSION=snapshot
before_install:
  - export PATH="$HOME/bin:$PATH"
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
  - emacs --version
install:
  - cask install
script:
  - make compile test
